- app/src/main/java/com/it235/nureserved/ui/authscreenui/LoginScreen.kt
- app/src/main/java/com/it235/nureserved/ui/authscreenui/SignUpScreen.kt
- Remove unused variable for font (signup screen)
- contentDescription parameter set to empty string since background image is for decorative purposes only (login and signup screen)
> Minimal cleanup of login and signup screens

- app/src/main/java/com/it235/nureserved/MainActivity.kt
- app/src/main/java/com/it235/nureserved/ui/ReservationFormScreen.kt
- app/src/main/java/com/it235/nureserved/ui/reservationscreenui/ReservationStatusScreen.kt
I include some a minor adjustment along with this branch
-  In reservation status screen, changed Column start padding from 20 to 15 dp
> Date picker fix

- app/src/main/java/com/it235/nureserved/MainActivity.kt
> Fix system config change causes the app to go to splash screen

- app/src/main/java/com/it235/nureserved/composables/Composables.kt
- app/src/main/java/com/it235/nureserved/ui/screens/ReservationFormScreen.kt
- app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationFilledOutFormScreen.kt
- app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationStatusScreen.kt
- app/src/main/java/com/it235/nureserved/ui/theme/Color.kt
> Make app theme responsive on system theme change

- app/src/main/java/com/it235/nureserved/ui/screens/RoomUsageRulesScreen.kt
- app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/HomeScreen.kt
- app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationStatusScreen.kt
This PR resolves #31, #36, #51,
> Fix navigation issues

- app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/HomeScreen.kt
> Show filter icon when user is in home tab only

- app/src/main/java/com/it235/nureserved/composables/Composables.kt
- app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/HomeScreen.kt
- app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/roomdetails/RoomDetails.kt
> Remove reserve tab in home screen and use FAB instead

- app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationFilledOutFormScreen.kt
> Add tracking number for reservation status screen

- app/src/main/java/com/it235/nureserved/ui/screens/ReservationFormScreen.kt
> Allow multiple selection and deselection of venue in reservation form screen

- app/src/main/java/com/it235/nureserved/ui/screens/ReservationFormScreen.kt
**Aim to fix:**
- #77
- #75 
- #74
> Some UI changes to reservation form screen

- app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/signup/EmailPasswordFieldsScreen.kt
- app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/signup/NamesFieldsScreen.kt
- app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/signup/ProgramStudentNumberFieldsScreen.kt
**Improved signup and login client-side validation constraint and provides real-time validation and feedback for users.**
**NamesFieldsScreen constraints**
- Check for empty inputs
- Names should be equal or greater than 2
- Leading and trailing spaces are prohibited
- Cannot contain symbols
- Cannot contain digits
- Valid separator for multiple names is space character only
**ProgramStudentNumberFieldsScreen constraints**
- Check if the user selected a program
- Check if the student number is in the correct format
**EmailPasswordFieldsScreen constraints**
- Check if the email input is empty
- Check if the email is in the correct format
- Check if the password is at least 8 characters long
- Check if the password contains at least 1 symbol
- Check if the password contains at least 1 digit …
> Signup and Login validation constraints

- app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/signup/EmailPasswordFieldsScreen.kt
> Revisions in retrieval and processing of user data on sign-up into Firestore Database

- app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/signup/NamesFieldsScreen.kt
> When signing up, convert person's name to proper name format

- app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/signup/ProgramStudentNumberFieldsScreen.kt
> Allow only specifc years when entering student number on registration

- app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationFilledOutFormScreen.kt
- app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationStatusScreen.kt
> Refactor some parts of Reservations tab

- app/src/main/java/com/it235/nureserved/screens/user/ReservationFormScreen.kt
> Prefill name fields on reservation form based on the user account details

- app/src/main/java/com/it235/nureserved/screens/user/ReservationFormScreen.kt
> Fix and improve the category divider and floor labels in the venue section of reservation form

- app/src/main/java/com/it235/nureserved/screens/user/ReservationFormScreen.kt
> Fix unreadable value of name fields in reseravation form when in dark mode 

- app/src/main/java/com/it235/nureserved/data/UserData.kt
- app/src/main/java/com/it235/nureserved/screens/core/authscreenui/LoginScreen.kt
Resolves #157 
Warning: Implementing this in actual system is NOT RECOMMENDED as anyone can easily change these values to access admin features even if the logged in account type is not an admin. This insecure implementation is for school project purposes only and is not meant to be used for an actual working reservation system.
> Redirect to admin screen if the logged in account is an admin

- app/build.gradle.kts
- app/src/main/java/com/it235/nureserved/MainActivity.kt
- app/src/main/java/com/it235/nureserved/preferences/ThemePreferences.kt
- app/src/main/java/com/it235/nureserved/screens/admin/floor_rooms/FloorRoomsScreen.kt
- app/src/main/java/com/it235/nureserved/screens/admin/home/AdminHomeScreen.kt
- app/src/main/java/com/it235/nureserved/screens/core/RoomDetails.kt
- app/src/main/java/com/it235/nureserved/screens/core/SharedComposables.kt
- app/src/main/java/com/it235/nureserved/screens/core/authscreenui/LoginScreen.kt
- app/src/main/java/com/it235/nureserved/screens/core/authscreenui/signup/EmailPasswordFieldsScreen.kt
- app/src/main/java/com/it235/nureserved/screens/core/authscreenui/signup/NamesFieldsScreen.kt
- app/src/main/java/com/it235/nureserved/screens/core/authscreenui/signup/ProgramStudentNumberFieldsScreen.kt
- app/src/main/java/com/it235/nureserved/screens/core/authscreenui/signup/RolesFieldScreen.kt
- app/src/main/java/com/it235/nureserved/screens/core/authscreenui/signup/SchoolFieldScreen.kt
- app/src/main/java/com/it235/nureserved/screens/user/homesreenui/HomeScreen.kt
- app/src/main/java/com/it235/nureserved/ui/theme/Theme.kt
- gradle/libs.versions.toml
> Add ability to change app theme

- app/src/main/java/com/it235/nureserved/MainActivity.kt
Needs further testing since there are instances that it doesn't work
> Fix login route redirecting to user instead of admin

- app/src/main/java/com/it235/nureserved/MainActivity.kt
- app/src/main/java/com/it235/nureserved/domain/auth/AuthService.kt
- app/src/main/java/com/it235/nureserved/domain/reservation/ReservationDataMapper.kt
- app/src/main/java/com/it235/nureserved/domain/reservation/ReservationManager.kt
- app/src/main/java/com/it235/nureserved/screens/admin/reservations/ReservationFormDetails.kt
- app/src/main/java/com/it235/nureserved/screens/admin/reservations/ReservationFormDetailsViewModel.kt
- app/src/main/java/com/it235/nureserved/screens/admin/reservations/ReservationsHistoryScreen.kt
- app/src/main/java/com/it235/nureserved/screens/admin/reservations/ReservationsHistoryScreenViewModel.kt
- app/src/main/java/com/it235/nureserved/screens/admin/reservations/ReservationsSharedViewModel.kt
- app/src/main/java/com/it235/nureserved/screens/admin/reservations/ReservationsStatusScreen.kt
- app/src/main/java/com/it235/nureserved/screens/admin/reservations/ReservationsStatusScreenViewModel.kt
- app/src/main/java/com/it235/nureserved/screens/shared/SharedComposables.kt
- app/src/main/java/com/it235/nureserved/screens/user/reservations/ReservationStatusScreen.kt
Bugs:
- Fixed via 3dba256bac85046ff862ad772df75eefc10a3828 ~~List of reservations doesn't update after approving or declining a request.~~
> Add working system for managing reservation requests on admin
